# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve details and status of a specific threat hunt"


class Input:
    HUNT_ID = "hunt_id"


class Output:
    HUNT_DETAILS = "hunt_details"


class GetHuntInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hunt_id": {
      "type": "string",
      "title": "Hunt ID",
      "description": "The unique identifier of the hunt",
      "order": 1
    }
  },
  "required": [
    "hunt_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetHuntOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hunt_details": {
      "$ref": "#/definitions/hunt_details",
      "title": "Hunt Details",
      "description": "Hunt configuration, state, and statistics",
      "order": 1
    }
  },
  "definitions": {
    "hunt_details": {
      "type": "object",
      "title": "hunt_details",
      "properties": {
        "hunt_id": {
          "type": "string",
          "title": "Hunt ID",
          "order": 1
        },
        "state": {
          "type": "string",
          "title": "State",
          "order": 2
        },
        "statistics": {
          "type": "object",
          "title": "Statistics",
          "order": 3
        },
        "configuration": {
          "type": "object",
          "title": "Configuration",
          "order": 4
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
