# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "List artifact collection flows for a specific client"


class Input:
    CLIENT_ID = "client_id"
    CREATOR = "creator"
    LIMIT = "limit"


class Output:
    COUNT = "count"
    FLOWS = "flows"


class ListFlowsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client",
      "order": 1
    },
    "creator": {
      "type": "string",
      "title": "Creator",
      "description": "Filter by flow creator username",
      "placeholder": "admin@example.com",
      "order": 2
    },
    "limit": {
      "type": "integer",
      "title": "Limit",
      "description": "Maximum number of results to return",
      "default": 50,
      "order": 3
    }
  },
  "required": [
    "client_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListFlowsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "count": {
      "type": "integer",
      "title": "Count",
      "description": "Number of flows returned",
      "order": 2
    },
    "flows": {
      "type": "array",
      "title": "Flows",
      "description": "List of flows for the client",
      "items": {
        "$ref": "#/definitions/flow"
      },
      "order": 1
    }
  },
  "definitions": {
    "flow": {
      "type": "object",
      "title": "flow",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "order": 1
        },
        "session_id": {
          "type": "string",
          "title": "Session ID",
          "order": 2
        },
        "create_time": {
          "type": "integer",
          "title": "Create Time",
          "order": 3
        },
        "state": {
          "type": "string",
          "title": "State",
          "order": 4
        },
        "total_requests": {
          "type": "integer",
          "title": "Total Requests",
          "order": 5
        },
        "outstanding_requests": {
          "type": "integer",
          "title": "Outstanding Requests",
          "order": 6
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
