# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Attach a file to an existing ticket via an action note"


class Input:
    CONTENT = "content"
    FILENAME = "filename"
    HIDDENFROMUSER = "hiddenfromuser"
    NOTE = "note"
    TICKET_ID = "ticket_id"


class Output:
    ACTION = "action"


class AttachFileToTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "content": {
      "type": "string",
      "format": "bytes",
      "displayType": "bytes",
      "title": "Content",
      "description": "Base64-encoded content of the file to attach",
      "order": 3
    },
    "filename": {
      "type": "string",
      "title": "Filename",
      "description": "Name of the file to attach (e.g. screenshot.png)",
      "order": 2
    },
    "hiddenfromuser": {
      "type": "boolean",
      "title": "Hidden from User",
      "description": "Whether the attachment action should be hidden from the end user",
      "default": false,
      "order": 5
    },
    "note": {
      "type": "string",
      "title": "Note",
      "description": "Optional note to include with the attachment",
      "order": 4
    },
    "ticket_id": {
      "type": "integer",
      "title": "Ticket ID",
      "description": "ID of the ticket to attach the file to",
      "order": 1
    }
  },
  "required": [
    "content",
    "filename",
    "ticket_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AttachFileToTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "action": {
      "$ref": "#/definitions/ticket_action",
      "title": "Action",
      "description": "The action created with the attachment",
      "order": 1
    }
  },
  "required": [
    "action"
  ],
  "definitions": {
    "ticket_action": {
      "type": "object",
      "title": "ticket_action",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique ID of the action",
          "order": 1
        },
        "ticket_id": {
          "type": "integer",
          "title": "Ticket ID",
          "description": "ID of the ticket this action belongs to",
          "order": 2
        },
        "who": {
          "type": "string",
          "title": "Who",
          "description": "Name of the person who performed the action",
          "order": 3
        },
        "note": {
          "type": "string",
          "title": "Note",
          "description": "Content of the action note",
          "order": 4
        },
        "hiddenfromuser": {
          "type": "boolean",
          "title": "Hidden from User",
          "description": "Whether the action is hidden from the end user",
          "order": 5
        },
        "outcome": {
          "type": "string",
          "title": "Outcome",
          "description": "Outcome of the action",
          "order": 6
        },
        "actiondate": {
          "type": "string",
          "title": "Action Date",
          "description": "Timestamp of the action",
          "order": 7
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
