# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve address objects from a FortiManager ADOM with optional filtering"


class Input:
    ADOM = "adom"
    FQDN_FILTER = "fqdn_filter"
    NAME_FILTER = "name_filter"
    SUBNET_FILTER = "subnet_filter"


class Output:
    ADDRESS_OBJECTS = "address_objects"


class GetAddressObjectsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain to query. If provided, overrides the ADOM configured in the connection",
      "order": 4
    },
    "fqdn_filter": {
      "type": "string",
      "title": "FQDN Filter",
      "description": "Optional FQDN value to filter address objects (case-insensitive exact match)",
      "order": 3
    },
    "name_filter": {
      "type": "string",
      "title": "Name Filter",
      "description": "Optional name to filter address objects (case-insensitive exact match)",
      "order": 1
    },
    "subnet_filter": {
      "type": "string",
      "title": "Subnet Filter",
      "description": "Optional subnet value to filter address objects (case-insensitive exact match)",
      "order": 2
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetAddressObjectsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_objects": {
      "type": "array",
      "title": "Address Objects",
      "description": "List of address objects matching the specified filters",
      "items": {
        "$ref": "#/definitions/address_object"
      },
      "order": 1
    }
  },
  "required": [
    "address_objects"
  ],
  "definitions": {
    "address_object": {
      "type": "object",
      "title": "address_object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Address object name",
          "order": 1
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Address type: ipmask, FQDN, iprange",
          "order": 2
        },
        "subnet": {
          "type": "string",
          "title": "Subnet",
          "description": "Subnet in CIDR notation (for ipmask type)",
          "order": 3
        },
        "fqdn": {
          "type": "string",
          "title": "FQDN",
          "description": "Fully qualified domain name (for FQDN type)",
          "order": 4
        },
        "start_ip": {
          "type": "string",
          "title": "Start IP",
          "description": "Range start IP (for iprange type)",
          "order": 5
        },
        "end_ip": {
          "type": "string",
          "title": "End IP",
          "description": "Range end IP (for iprange type)",
          "order": 6
        },
        "comment": {
          "type": "string",
          "title": "Comment",
          "description": "Optional comment",
          "order": 7
        },
        "associated_interface": {
          "type": "string",
          "title": "Associated Interface",
          "description": "Associated network interface",
          "order": 8
        }
      },
      "required": [
        "name",
        "type"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
