# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve the status and details of a specific flow collection"


class Input:
    CLIENT_ID = "client_id"
    FLOW_ID = "flow_id"


class Output:
    FLOW = "flow"


class GetFlowInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client",
      "order": 1
    },
    "flow_id": {
      "type": "string",
      "title": "Flow ID",
      "description": "The unique identifier of the flow",
      "order": 2
    }
  },
  "required": [
    "client_id",
    "flow_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetFlowOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "flow": {
      "$ref": "#/definitions/flow",
      "title": "Flow",
      "description": "Flow collection details and status",
      "order": 1
    }
  },
  "definitions": {
    "flow": {
      "type": "object",
      "title": "flow",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "order": 1
        },
        "session_id": {
          "type": "string",
          "title": "Session ID",
          "order": 2
        },
        "create_time": {
          "type": "integer",
          "title": "Create Time",
          "order": 3
        },
        "state": {
          "type": "string",
          "title": "State",
          "order": 4
        },
        "total_requests": {
          "type": "integer",
          "title": "Total Requests",
          "order": 5
        },
        "outstanding_requests": {
          "type": "integer",
          "title": "Outstanding Requests",
          "order": 6
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
