# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "List enrolled devices from Zscaler Client Connector with an optional username filter to locate a specific user's device. Returns device details including the UDID needed for OTP generation"


class Input:
    OS_TYPE = "os_type"
    USERNAME = "username"


class Output:
    DEVICES = "devices"


class GetEnrolledDevicesInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "os_type": {
      "type": "string",
      "title": "OS Type",
      "description": "Filter devices by operating system type",
      "enum": [
        "Windows",
        "macOS",
        "iOS",
        "Android",
        "Linux"
      ],
      "order": 2
    },
    "username": {
      "type": "string",
      "title": "Username",
      "description": "Filter devices by username (email address). If provided, only devices belonging to this user are returned",
      "placeholder": "user@example.com",
      "order": 1
    }
  },
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetEnrolledDevicesOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "devices": {
      "type": "array",
      "title": "Devices",
      "description": "List of enrolled devices matching the filter criteria",
      "items": {
        "type": "object"
      },
      "order": 1
    }
  },
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
