# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve details for a specific Velociraptor client endpoint"


class Input:
    CLIENT_ID = "client_id"


class Output:
    CLIENT = "client"


class GetClientInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client",
      "order": 1
    }
  },
  "required": [
    "client_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetClientOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client": {
      "$ref": "#/definitions/client",
      "title": "Client",
      "description": "Client endpoint details",
      "order": 1
    }
  },
  "definitions": {
    "client": {
      "type": "object",
      "title": "client",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "order": 1
        },
        "hostname": {
          "type": "string",
          "title": "Hostname",
          "order": 2
        },
        "release": {
          "type": "string",
          "title": "Release",
          "order": 3
        },
        "architecture": {
          "type": "string",
          "title": "Architecture",
          "order": 4
        },
        "client_version": {
          "type": "string",
          "title": "Client Version",
          "order": 5
        },
        "system": {
          "type": "string",
          "title": "System",
          "order": 6
        },
        "first_seen_at": {
          "type": "integer",
          "title": "First Seen At",
          "order": 7
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
