# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "List tickets from Halo ITSM with optional filtering"


class Input:
    AGENT_ID = "agent_id"
    CLIENT_ID = "client_id"
    COUNT = "count"
    SEARCH = "search"
    STATUS_ID = "status_id"
    TICKETTYPE_ID = "tickettype_id"


class Output:
    TICKETS = "tickets"


class ListTicketsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "agent_id": {
      "type": "integer",
      "title": "Agent ID",
      "description": "Filter tickets by assigned agent ID",
      "order": 3
    },
    "client_id": {
      "type": "integer",
      "title": "Client ID",
      "description": "Filter tickets by client ID",
      "order": 4
    },
    "count": {
      "type": "integer",
      "title": "Count",
      "description": "Maximum number of tickets to return",
      "default": 50,
      "order": 5
    },
    "search": {
      "type": "string",
      "title": "Search",
      "description": "Search string to filter tickets",
      "placeholder": "Enter search term",
      "order": 6
    },
    "status_id": {
      "type": "integer",
      "title": "Status ID",
      "description": "Filter tickets by status ID",
      "order": 1
    },
    "tickettype_id": {
      "type": "integer",
      "title": "Ticket Type ID",
      "description": "Filter tickets by ticket type ID",
      "order": 2
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListTicketsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "tickets": {
      "type": "array",
      "title": "Tickets",
      "description": "List of tickets matching the filter criteria",
      "items": {
        "$ref": "#/definitions/ticket"
      },
      "order": 1
    }
  },
  "required": [
    "tickets"
  ],
  "definitions": {
    "ticket": {
      "type": "object",
      "title": "ticket",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique ID of the ticket",
          "order": 1
        },
        "summary": {
          "type": "string",
          "title": "Summary",
          "description": "Summary of the ticket",
          "order": 2
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Details of the ticket",
          "order": 3
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "ID of the ticket status",
          "order": 4
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "ID of the ticket priority",
          "order": 5
        },
        "tickettype_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "ID of the ticket type",
          "order": 6
        },
        "category_1": {
          "type": "string",
          "title": "Category",
          "description": "Primary category of the ticket",
          "order": 7
        },
        "category_2": {
          "type": "string",
          "title": "Subcategory",
          "description": "Subcategory of the ticket",
          "order": 8
        },
        "impact": {
          "type": "string",
          "title": "Impact",
          "description": "Impact level of the ticket",
          "order": 9
        },
        "urgency": {
          "type": "string",
          "title": "Urgency",
          "description": "Urgency level of the ticket",
          "order": 10
        },
        "user_id": {
          "type": "integer",
          "title": "User ID",
          "description": "ID of the user who raised the ticket",
          "order": 11
        },
        "user_name": {
          "type": "string",
          "title": "User Name",
          "description": "Name of the user who raised the ticket",
          "order": 12
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "ID of the agent assigned to the ticket",
          "order": 13
        },
        "agent_name": {
          "type": "string",
          "title": "Agent Name",
          "description": "Name of the agent assigned to the ticket",
          "order": 14
        },
        "team": {
          "type": "string",
          "title": "Team",
          "description": "Team assigned to the ticket",
          "order": 15
        },
        "dateoccurred": {
          "type": "string",
          "title": "Date Occurred",
          "description": "Date when the ticket was raised",
          "order": 16
        },
        "datecreated": {
          "type": "string",
          "title": "Date Created",
          "description": "Timestamp when the ticket was created",
          "order": 17
        },
        "lastupdate": {
          "type": "string",
          "title": "Last Update",
          "description": "Timestamp of the last update on the ticket",
          "order": 18
        },
        "closeddate": {
          "type": "string",
          "title": "Closed Date",
          "description": "Timestamp when the ticket was closed",
          "order": 19
        },
        "client_id": {
          "type": "integer",
          "title": "Client ID",
          "description": "ID of the client associated with the ticket",
          "order": 20
        },
        "client_name": {
          "type": "string",
          "title": "Client Name",
          "description": "Name of the client associated with the ticket",
          "order": 21
        },
        "site_id": {
          "type": "integer",
          "title": "Site ID",
          "description": "ID of the site associated with the ticket",
          "order": 22
        },
        "sla_id": {
          "type": "integer",
          "title": "SLA ID",
          "description": "ID of the SLA applied to the ticket",
          "order": 23
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
