# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve all address groups from a FortiManager ADOM with their member names"


class Input:
    ADOM = "adom"


class Output:
    ADDRESS_GROUPS = "address_groups"
    MESSAGE = "message"


class ListAddressGroupsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain to query. If provided, overrides the ADOM configured in the connection",
      "order": 1
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListAddressGroupsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_groups": {
      "type": "array",
      "title": "Address Groups",
      "description": "List of address groups in the ADOM with the names of their member address objects",
      "items": {
        "$ref": "#/definitions/address_group"
      },
      "order": 1
    },
    "message": {
      "type": "string",
      "title": "Message",
      "description": "Human-readable description of the result",
      "order": 2
    }
  },
  "required": [
    "address_groups"
  ],
  "definitions": {
    "address_group": {
      "type": "object",
      "title": "address_group",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Address group name",
          "order": 1
        },
        "member": {
          "type": "array",
          "title": "Member",
          "description": "List of member address object names",
          "items": {
            "type": "string"
          },
          "order": 2
        },
        "comment": {
          "type": "string",
          "title": "Comment",
          "description": "Optional comment",
          "order": 3
        }
      },
      "required": [
        "member",
        "name"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
