# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Send an authenticated request to a Zscaler OneAPI service and return the raw status code and response body without error handling, which allows a vendor request to be reproduced exactly when troubleshooting connectivity or permissions"


class Input:
    BODY = "body"
    METHOD = "method"
    PATH = "path"
    SERVICE = "service"


class Output:
    RESPONSE = "response"
    STATUS_CODE = "status_code"
    URL = "url"


class CustomApiRequestInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "body": {
      "type": "object",
      "title": "Body",
      "description": "Optional JSON body to send with the request. Ignored for GET requests",
      "order": 4
    },
    "method": {
      "type": "string",
      "title": "Method",
      "description": "The HTTP method to use. Write methods such as POST, PUT, PATCH and DELETE are able to modify configuration in the target tenant",
      "default": "GET",
      "enum": [
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE"
      ],
      "order": 2
    },
    "path": {
      "type": "string",
      "title": "Path",
      "description": "The endpoint path relative to the service prefix, specified without a leading slash",
      "placeholder": "web/policy/listByCompany",
      "order": 3
    },
    "service": {
      "type": "string",
      "title": "Service",
      "description": "The Zscaler OneAPI service to target, which determines the API path prefix that is prepended to the path",
      "enum": [
        "ZIA",
        "ZPA",
        "ZCC"
      ],
      "order": 1
    }
  },
  "required": [
    "method",
    "path",
    "service"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CustomApiRequestOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "response": {
      "type": "string",
      "title": "Response",
      "description": "The raw response body returned by the Zscaler API",
      "order": 3
    },
    "status_code": {
      "type": "integer",
      "title": "Status Code",
      "description": "The HTTP status code returned by the Zscaler API",
      "order": 1
    },
    "url": {
      "type": "string",
      "title": "URL",
      "description": "The full URL that was requested, for comparison against a known working request",
      "order": 2
    }
  },
  "required": [
    "status_code",
    "url"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
