# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add an action (note, comment, or update) to an existing ticket"


class Input:
    HIDDENFROMUSER = "hiddenfromuser"
    NOTE = "note"
    OUTCOME = "outcome"
    TICKET_ID = "ticket_id"


class Output:
    ACTION = "action"


class AddActionToTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hiddenfromuser": {
      "type": "boolean",
      "title": "Hidden from User",
      "description": "Whether this note should be hidden from the end user",
      "default": false,
      "order": 4
    },
    "note": {
      "type": "string",
      "title": "Note",
      "description": "Content of the action note in plain text or HTML",
      "order": 2
    },
    "outcome": {
      "type": "string",
      "title": "Outcome",
      "description": "Outcome of the action",
      "order": 3
    },
    "ticket_id": {
      "type": "integer",
      "title": "Ticket ID",
      "description": "ID of the ticket to add the action to",
      "order": 1
    }
  },
  "required": [
    "note",
    "ticket_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddActionToTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "action": {
      "$ref": "#/definitions/ticket_action",
      "title": "Action",
      "description": "The newly created action",
      "order": 1
    }
  },
  "required": [
    "action"
  ],
  "definitions": {
    "ticket_action": {
      "type": "object",
      "title": "ticket_action",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique ID of the action",
          "order": 1
        },
        "ticket_id": {
          "type": "integer",
          "title": "Ticket ID",
          "description": "ID of the ticket this action belongs to",
          "order": 2
        },
        "who": {
          "type": "string",
          "title": "Who",
          "description": "Name of the person who performed the action",
          "order": 3
        },
        "note": {
          "type": "string",
          "title": "Note",
          "description": "Content of the action note",
          "order": 4
        },
        "hiddenfromuser": {
          "type": "boolean",
          "title": "Hidden from User",
          "description": "Whether the action is hidden from the end user",
          "order": 5
        },
        "outcome": {
          "type": "string",
          "title": "Outcome",
          "description": "Outcome of the action",
          "order": 6
        },
        "actiondate": {
          "type": "string",
          "title": "Action Date",
          "description": "Timestamp of the action",
          "order": 7
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
