# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="microsoft_office365_email_security-rapid7_custom-plugin",
    version="4.1.2",
    description="The Microsoft Office 365 email security plugin adds utilities to help administrators manage their Office 365 instances. This plugin will allow administrators to take remediation actions across their organization",
    author="rapid7_custom",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={
        "console_scripts": [
            "icon_microsoft_office365_email_security = bin.icon_microsoft_office365_email_security:main"
        ]
    },
)
