# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve the one-time password (OTP) bundle for a specific enrolled device identified by its UDID. The OTP can be used for logout, exit, uninstall, or service disable operations"


class Input:
    UDID = "udid"


class Output:
    OTP = "otp"


class GetOneTimePasswordInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "udid": {
      "type": "string",
      "title": "UDID",
      "description": "The unique device identifier (UDID) of the enrolled device. Obtain this from the Get Enrolled Devices action",
      "placeholder": "abc123-def456-ghi789",
      "order": 1
    }
  },
  "required": [
    "udid"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetOneTimePasswordOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "otp": {
      "type": "object",
      "title": "OTP",
      "description": "The one-time password bundle for the device containing passwords for various operations",
      "order": 1
    }
  },
  "required": [
    "otp"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
