# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add a label to a client for tracking during incident response"


class Input:
    CLIENT_ID = "client_id"
    LABEL = "label"


class Output:
    LABEL_RESPONSE = "label_response"


class AddLabelInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client",
      "order": 1
    },
    "label": {
      "type": "string",
      "title": "Label",
      "description": "The label to add to the client",
      "placeholder": "compromised",
      "order": 2
    }
  },
  "required": [
    "client_id",
    "label"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddLabelOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "label_response": {
      "$ref": "#/definitions/label_response",
      "title": "Label Response",
      "description": "Confirmation of the label addition",
      "order": 1
    }
  },
  "definitions": {
    "label_response": {
      "type": "object",
      "title": "label_response",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "order": 1
        },
        "label": {
          "type": "string",
          "title": "Label",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
