# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = (
        "Retrieve VPN gateway bypass entries from ZCC application profiles for auditing shared-hosting/CDN IP conflicts"
    )


class Input:
    pass


class Output:
    PROFILES = "profiles"


class GetVpnGatewayBypassesInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetVpnGatewayBypassesOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "profiles": {
      "type": "array",
      "title": "Profiles",
      "description": "List of application profiles with VPN gateway bypass entries",
      "items": {
        "$ref": "#/definitions/vpn_gateway_profile"
      },
      "order": 1
    }
  },
  "required": [
    "profiles"
  ],
  "definitions": {
    "vpn_gateway_profile": {
      "type": "object",
      "title": "vpn_gateway_profile",
      "properties": {
        "profile_id": {
          "type": "string",
          "title": "Profile ID",
          "description": "The application profile ID",
          "order": 1
        },
        "profile_name": {
          "type": "string",
          "title": "Profile Name",
          "description": "The application profile name",
          "order": 2
        },
        "vpn_gateways": {
          "type": "array",
          "title": "VPN Gateways",
          "description": "List of VPN gateway bypass entries",
          "items": {
            "$ref": "#/definitions/vpn_gateway_entry"
          },
          "order": 3
        }
      },
      "required": [
        "profile_id",
        "profile_name",
        "vpn_gateways"
      ]
    },
    "vpn_gateway_entry": {
      "type": "object",
      "title": "vpn_gateway_entry",
      "properties": {
        "hostname": {
          "type": "string",
          "title": "Hostname",
          "description": "The hostname of the VPN gateway bypass entry",
          "order": 1
        },
        "ip": {
          "type": "string",
          "title": "IP",
          "description": "The IP address of the VPN gateway bypass entry",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "The type of entry (e.g., \"hostname\", \"ip\")",
          "order": 3
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
