# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    API_KEY = "api_key"
    ORG_ID = "org_id"
    REGION = "region"


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api_key": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Key",
      "description": "Rapid7 Platform API key",
      "order": 3
    },
    "org_id": {
      "type": "string",
      "title": "Organization ID",
      "description": "Velociraptor organization ID",
      "placeholder": "686a33ec-88b9-4f84-bddf-2a1fb0fecb85",
      "order": 2
    },
    "region": {
      "type": "string",
      "title": "Region",
      "description": "Rapid7 platform region",
      "enum": [
        "us",
        "us2",
        "us3",
        "eu",
        "au",
        "ca",
        "ap",
        "jp"
      ],
      "order": 1
    }
  },
  "required": [
    "api_key",
    "org_id",
    "region"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "required": [
        "secretKey"
      ],
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "description": "The shared secret key",
          "format": "password",
          "displayType": "password"
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
