# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Launch an artifact collection on a specific client endpoint"


class Input:
    ARTIFACTS = "artifacts"
    CLIENT_ID = "client_id"
    MAX_ROWS = "max_rows"
    TIMEOUT = "timeout"
    URGENT = "urgent"


class Output:
    FLOW_ID = "flow_id"


class CreateFlowInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "artifacts": {
      "type": "array",
      "title": "Artifacts",
      "description": "List of artifact names to collect",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client to collect from",
      "order": 1
    },
    "max_rows": {
      "type": "integer",
      "title": "Max Rows",
      "description": "Maximum number of rows to collect per artifact",
      "order": 5
    },
    "timeout": {
      "type": "integer",
      "title": "Timeout",
      "description": "Collection timeout in seconds",
      "default": 600,
      "order": 4
    },
    "urgent": {
      "type": "boolean",
      "title": "Urgent",
      "description": "Whether to prioritize this collection",
      "default": false,
      "order": 3
    }
  },
  "required": [
    "artifacts",
    "client_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateFlowOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "flow_id": {
      "type": "string",
      "title": "Flow ID",
      "description": "The unique identifier of the created flow",
      "order": 1
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
