# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Send a prompt to ChatGPT and receive a response"


class Input:
    MAX_TOKENS = "max_tokens"
    PROMPT = "prompt"
    SYSTEM_MESSAGE = "system_message"
    TEMPERATURE = "temperature"


class Output:
    RESPONSE = "response"
    USAGE = "usage"


class AskChatgptInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "max_tokens": {
      "type": "integer",
      "title": "Max Tokens",
      "description": "Maximum number of tokens in the response (higher values allow longer responses)",
      "default": 2048,
      "order": 3
    },
    "prompt": {
      "type": "string",
      "title": "Prompt",
      "description": "The prompt or question to send to ChatGPT",
      "placeholder": "Enter your prompt",
      "order": 1
    },
    "system_message": {
      "type": "string",
      "title": "System Message",
      "description": "Optional system message to set the behavior and context for the AI assistant",
      "placeholder": "Enter system instructions",
      "order": 2
    },
    "temperature": {
      "type": "number",
      "title": "Temperature",
      "description": "Controls randomness in the response (0.0 = deterministic, 2.0 = most random)",
      "default": 0.7,
      "order": 4
    }
  },
  "required": [
    "prompt"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AskChatgptOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "response": {
      "type": "string",
      "title": "Response",
      "description": "The text response from ChatGPT",
      "order": 1
    },
    "usage": {
      "type": "object",
      "title": "Usage",
      "description": "Token usage details for the request",
      "order": 2
    }
  },
  "required": [
    "response",
    "usage"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
