# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get details of a specific ticket by ID"


class Input:
    TICKET_ID = "ticket_id"


class Output:
    TICKET = "ticket"


class GetTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ticket_id": {
      "type": "integer",
      "title": "Ticket ID",
      "description": "ID of the ticket to retrieve",
      "order": 1
    }
  },
  "required": [
    "ticket_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ticket": {
      "$ref": "#/definitions/ticket",
      "title": "Ticket",
      "description": "The ticket details",
      "order": 1
    }
  },
  "required": [
    "ticket"
  ],
  "definitions": {
    "ticket": {
      "type": "object",
      "title": "ticket",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique ID of the ticket",
          "order": 1
        },
        "summary": {
          "type": "string",
          "title": "Summary",
          "description": "Summary of the ticket",
          "order": 2
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Details of the ticket",
          "order": 3
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "ID of the ticket status",
          "order": 4
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "ID of the ticket priority",
          "order": 5
        },
        "tickettype_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "ID of the ticket type",
          "order": 6
        },
        "category_1": {
          "type": "string",
          "title": "Category",
          "description": "Primary category of the ticket",
          "order": 7
        },
        "category_2": {
          "type": "string",
          "title": "Subcategory",
          "description": "Subcategory of the ticket",
          "order": 8
        },
        "impact": {
          "type": "string",
          "title": "Impact",
          "description": "Impact level of the ticket",
          "order": 9
        },
        "urgency": {
          "type": "string",
          "title": "Urgency",
          "description": "Urgency level of the ticket",
          "order": 10
        },
        "user_id": {
          "type": "integer",
          "title": "User ID",
          "description": "ID of the user who raised the ticket",
          "order": 11
        },
        "user_name": {
          "type": "string",
          "title": "User Name",
          "description": "Name of the user who raised the ticket",
          "order": 12
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "ID of the agent assigned to the ticket",
          "order": 13
        },
        "agent_name": {
          "type": "string",
          "title": "Agent Name",
          "description": "Name of the agent assigned to the ticket",
          "order": 14
        },
        "team": {
          "type": "string",
          "title": "Team",
          "description": "Team assigned to the ticket",
          "order": 15
        },
        "dateoccurred": {
          "type": "string",
          "title": "Date Occurred",
          "description": "Date when the ticket was raised",
          "order": 16
        },
        "datecreated": {
          "type": "string",
          "title": "Date Created",
          "description": "Timestamp when the ticket was created",
          "order": 17
        },
        "lastupdate": {
          "type": "string",
          "title": "Last Update",
          "description": "Timestamp of the last update on the ticket",
          "order": 18
        },
        "closeddate": {
          "type": "string",
          "title": "Closed Date",
          "description": "Timestamp when the ticket was closed",
          "order": 19
        },
        "client_id": {
          "type": "integer",
          "title": "Client ID",
          "description": "ID of the client associated with the ticket",
          "order": 20
        },
        "client_name": {
          "type": "string",
          "title": "Client Name",
          "description": "Name of the client associated with the ticket",
          "order": 21
        },
        "site_id": {
          "type": "integer",
          "title": "Site ID",
          "description": "ID of the site associated with the ticket",
          "order": 22
        },
        "sla_id": {
          "type": "integer",
          "title": "SLA ID",
          "description": "ID of the SLA applied to the ticket",
          "order": 23
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
