# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "List threat hunts with optional state filter"


class Input:
    LIMIT = "limit"
    STATE = "state"


class Output:
    COUNT = "count"
    HUNTS = "hunts"


class ListHuntsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "limit": {
      "type": "integer",
      "title": "Limit",
      "description": "Maximum number of results to return",
      "default": 50,
      "order": 2
    },
    "state": {
      "type": "string",
      "title": "State",
      "description": "Filter hunts by state",
      "enum": [
        "UNSET",
        "PAUSED",
        "RUNNING",
        "STOPPED",
        "ARCHIVED"
      ],
      "order": 1
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListHuntsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "count": {
      "type": "integer",
      "title": "Count",
      "description": "Number of hunts returned",
      "order": 2
    },
    "hunts": {
      "type": "array",
      "title": "Hunts",
      "description": "List of hunts",
      "items": {
        "$ref": "#/definitions/hunt"
      },
      "order": 1
    }
  },
  "definitions": {
    "hunt": {
      "type": "object",
      "title": "hunt",
      "properties": {
        "hunt_id": {
          "type": "string",
          "title": "Hunt ID",
          "order": 1
        },
        "hunt_description": {
          "type": "string",
          "title": "Hunt Description",
          "order": 2
        },
        "creator": {
          "type": "string",
          "title": "Creator",
          "order": 3
        },
        "state": {
          "type": "string",
          "title": "State",
          "order": 4
        },
        "create_time": {
          "type": "integer",
          "title": "Create Time",
          "order": 5
        },
        "expires": {
          "type": "integer",
          "title": "Expires",
          "order": 6
        },
        "artifacts": {
          "type": "array",
          "title": "Artifacts",
          "items": {
            "type": "string"
          },
          "order": 7
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
