# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Generate a concise executive summary of a security incident from provided alert data or notes"


class Input:
    AUDIENCE = "audience"
    INCIDENT_DATA = "incident_data"
    SEVERITY = "severity"


class Output:
    KEY_FINDINGS = "key_findings"
    SUMMARY = "summary"
    TIMELINE = "timeline"


class SummarizeIncidentInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "audience": {
      "type": "string",
      "title": "Audience",
      "description": "Target audience for the summary to adjust technical depth",
      "default": "technical",
      "enum": [
        "executive",
        "technical",
        "both"
      ],
      "order": 3
    },
    "incident_data": {
      "type": "string",
      "title": "Incident Data",
      "description": "Raw incident data, alert details, or analyst notes to summarize",
      "placeholder": "Paste incident data, alerts, or notes",
      "order": 1
    },
    "severity": {
      "type": "string",
      "title": "Severity",
      "description": "Severity level of the incident for context",
      "enum": [
        "critical",
        "high",
        "medium",
        "low",
        "informational"
      ],
      "order": 2
    }
  },
  "required": [
    "incident_data"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SummarizeIncidentOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "key_findings": {
      "type": "array",
      "title": "Key Findings",
      "description": "List of key findings extracted from the incident data",
      "items": {
        "type": "string"
      },
      "order": 3
    },
    "summary": {
      "type": "string",
      "title": "Summary",
      "description": "Concise incident summary tailored to the specified audience",
      "order": 1
    },
    "timeline": {
      "type": "string",
      "title": "Timeline",
      "description": "Extracted timeline of events if identifiable from the data",
      "order": 2
    }
  },
  "required": [
    "key_findings",
    "summary",
    "timeline"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
