# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Create a new address object in a FortiManager ADOM"


class Input:
    ADDRESS = "address"
    ADDRESS_OBJECT_NAME = "address_object_name"
    ADOM = "adom"
    SKIP_RFC1918 = "skip_rfc1918"
    WHITELIST = "whitelist"


class Output:
    ADDRESS_OBJECT = "address_object"
    SUCCESS = "success"


class CreateAddressObjectInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address": {
      "type": "string",
      "title": "Address",
      "description": "The address to assign to the address object. Accepts an IP address, CIDR notation, or fully qualified domain name",
      "order": 1
    },
    "address_object_name": {
      "type": "string",
      "title": "Address Object Name",
      "description": "Optional name for the address object. If not provided, the address value will be used as the name",
      "order": 2
    },
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 5
    },
    "skip_rfc1918": {
      "type": "boolean",
      "title": "Skip RFC 1918 (Private) IP Addresses",
      "description": "Skip creation for private IP addresses as defined in RFC 1918",
      "default": true,
      "order": 4
    },
    "whitelist": {
      "type": "array",
      "title": "Whitelist",
      "description": "List of addresses that should not be blocked. Supports IP addresses, CIDR ranges, and domain names",
      "items": {
        "type": "string"
      },
      "order": 3
    }
  },
  "required": [
    "address",
    "skip_rfc1918"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateAddressObjectOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_object": {
      "$ref": "#/definitions/address_object",
      "title": "Address Object",
      "description": "Details of the created address object",
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Boolean value indicating whether the address object was created. Returns false if the address was skipped due to whitelist or RFC 1918 filtering",
      "order": 1
    }
  },
  "required": [
    "success"
  ],
  "definitions": {
    "address_object": {
      "type": "object",
      "title": "address_object",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Address object name",
          "order": 1
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Address type: ipmask, FQDN, iprange",
          "order": 2
        },
        "subnet": {
          "type": "string",
          "title": "Subnet",
          "description": "Subnet in CIDR notation (for ipmask type)",
          "order": 3
        },
        "fqdn": {
          "type": "string",
          "title": "FQDN",
          "description": "Fully qualified domain name (for FQDN type)",
          "order": 4
        },
        "start_ip": {
          "type": "string",
          "title": "Start IP",
          "description": "Range start IP (for iprange type)",
          "order": 5
        },
        "end_ip": {
          "type": "string",
          "title": "End IP",
          "description": "Range end IP (for iprange type)",
          "order": 6
        },
        "comment": {
          "type": "string",
          "title": "Comment",
          "description": "Optional comment",
          "order": 7
        },
        "associated_interface": {
          "type": "string",
          "title": "Associated Interface",
          "description": "Associated network interface",
          "order": 8
        }
      },
      "required": [
        "name",
        "type"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
