# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Remove entries from the Tenant Allow/Block List by specifying the list type and values to remove"


class Input:
    ENTRIES = "entries"
    LIST_TYPE = "list_type"


class Output:
    SUCCESS = "success"


class RemoveTenantAllowBlockListEntryInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "entries": {
      "type": "array",
      "title": "Entries",
      "description": "Values to remove from the list. Must match existing entry values exactly",
      "placeholder": "evil@example.com",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "list_type": {
      "type": "string",
      "title": "List Type",
      "description": "The type of entries to remove",
      "enum": [
        "Sender",
        "Url",
        "FileHash",
        "IP"
      ],
      "order": 1
    }
  },
  "required": [
    "entries",
    "list_type"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class RemoveTenantAllowBlockListEntryOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the entries were removed successfully",
      "order": 1
    }
  },
  "required": [
    "success"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
