# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Search and list Velociraptor client endpoints with optional filters"


class Input:
    HOSTNAME = "hostname"
    LABEL = "label"
    LIMIT = "limit"
    OS = "os"
    STATUS = "status"


class Output:
    CLIENTS = "clients"
    COUNT = "count"


class ListClientsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hostname": {
      "type": "string",
      "title": "Hostname",
      "description": "Filter by hostname substring",
      "placeholder": "WORKSTATION-01",
      "order": 1
    },
    "label": {
      "type": "string",
      "title": "Label",
      "description": "Filter by client label",
      "placeholder": "compromised",
      "order": 3
    },
    "limit": {
      "type": "integer",
      "title": "Limit",
      "description": "Maximum number of results to return",
      "default": 100,
      "order": 5
    },
    "os": {
      "type": "string",
      "title": "Operating System",
      "description": "Filter by operating system",
      "placeholder": "windows",
      "order": 2
    },
    "status": {
      "type": "string",
      "title": "Status",
      "description": "Filter by client online status",
      "default": "ALL",
      "enum": [
        "ALL",
        "ONLINE",
        "OFFLINE"
      ],
      "order": 4
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListClientsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "clients": {
      "type": "array",
      "title": "Clients",
      "description": "List of client endpoints matching the search criteria",
      "items": {
        "$ref": "#/definitions/client"
      },
      "order": 1
    },
    "count": {
      "type": "integer",
      "title": "Count",
      "description": "Number of clients returned",
      "order": 2
    }
  },
  "definitions": {
    "client": {
      "type": "object",
      "title": "client",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "order": 1
        },
        "hostname": {
          "type": "string",
          "title": "Hostname",
          "order": 2
        },
        "release": {
          "type": "string",
          "title": "Release",
          "order": 3
        },
        "architecture": {
          "type": "string",
          "title": "Architecture",
          "order": 4
        },
        "client_version": {
          "type": "string",
          "title": "Client Version",
          "order": 5
        },
        "system": {
          "type": "string",
          "title": "System",
          "order": 6
        },
        "first_seen_at": {
          "type": "integer",
          "title": "First Seen At",
          "order": 7
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
