# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="halo_itsm-rapid7-plugin",
    version="1.1.0",
    description="Halo ITSM is a cloud-based IT Service Management platform that provides ticket management, asset tracking, and service desk capabilities",
    author="rapid7",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_halo_itsm = bin.icon_halo_itsm:main"]},
)
