# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve an address group and the names of its member address objects"


class Input:
    ADOM = "adom"
    GROUP = "group"


class Output:
    ADDRESS_GROUP = "address_group"
    MESSAGE = "message"


class GetAddressGroupInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 2
    },
    "group": {
      "type": "string",
      "title": "Group",
      "description": "Name of the address group to retrieve",
      "order": 1
    }
  },
  "required": [
    "group"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetAddressGroupOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_group": {
      "$ref": "#/definitions/address_group",
      "title": "Address Group",
      "description": "The address group with the names of its member address objects",
      "order": 1
    },
    "message": {
      "type": "string",
      "title": "Message",
      "description": "Human-readable description of the result",
      "order": 2
    }
  },
  "required": [
    "address_group"
  ],
  "definitions": {
    "address_group": {
      "type": "object",
      "title": "address_group",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Address group name",
          "order": 1
        },
        "member": {
          "type": "array",
          "title": "Member",
          "description": "List of member address object names",
          "items": {
            "type": "string"
          },
          "order": 2
        },
        "comment": {
          "type": "string",
          "title": "Comment",
          "description": "Optional comment",
          "order": 3
        }
      },
      "required": [
        "member",
        "name"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
