# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    ADOM = "adom"
    API_KEY = "api_key"
    AUTHENTICATION_TYPE = "authentication_type"
    HOSTNAME = "hostname"
    PASSWORD = "password"
    SSL_VERIFY = "ssl_verify"
    USERNAME = "username"


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Default Administrative Domain (ADOM) name",
      "default": "root",
      "order": 7
    },
    "api_key": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Key",
      "description": "API token for Bearer authentication (required when authentication type is API Token)",
      "order": 3
    },
    "authentication_type": {
      "type": "string",
      "title": "Authentication Type",
      "description": "Authentication method to use when connecting to FortiManager",
      "default": "API Token",
      "enum": [
        "API Token",
        "Session-Based"
      ],
      "order": 2
    },
    "hostname": {
      "type": "string",
      "title": "Hostname",
      "description": "FortiManager hostname or IP address (e.g. fortimanager.example.com, 192.168.1.1, fortimanager.example.com:8443)",
      "order": 1
    },
    "password": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "Password",
      "description": "Admin password for session-based authentication (required when authentication type is Session-Based)",
      "order": 5
    },
    "ssl_verify": {
      "type": "boolean",
      "title": "SSL Verify",
      "description": "Validate TLS certificate when connecting to FortiManager",
      "default": false,
      "order": 6
    },
    "username": {
      "type": "string",
      "title": "Username",
      "description": "Admin username for session-based authentication (required when authentication type is Session-Based)",
      "order": 4
    }
  },
  "required": [
    "adom",
    "authentication_type",
    "hostname",
    "ssl_verify"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "required": [
        "secretKey"
      ],
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "description": "The shared secret key",
          "format": "password",
          "displayType": "password"
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
