# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Remove a label from a client"


class Input:
    CLIENT_ID = "client_id"
    LABEL = "label"


class Output:
    SUCCESS = "success"


class RemoveLabelInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "The unique identifier of the client",
      "order": 1
    },
    "label": {
      "type": "string",
      "title": "Label",
      "description": "The label to remove from the client",
      "placeholder": "compromised",
      "order": 2
    }
  },
  "required": [
    "client_id",
    "label"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class RemoveLabelOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the label was successfully removed",
      "order": 1
    }
  },
  "required": [
    "success"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
