# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Install a policy package to managed FortiGate devices or device groups"


class Input:
    ADOM = "adom"
    POLICY_PACKAGE = "policy_package"
    TARGET_DEVICE_GROUPS = "target_device_groups"
    TARGET_DEVICES = "target_devices"


class Output:
    TASK_ID = "task_id"


class InstallPolicyPackageInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 4
    },
    "policy_package": {
      "type": "string",
      "title": "Policy Package",
      "description": "Name of the policy package to install",
      "order": 1
    },
    "target_device_groups": {
      "type": "array",
      "title": "Target Device Groups",
      "description": "List of target device group names to install the policy package to. At least one target device or target device group must be provided",
      "items": {
        "type": "string"
      },
      "order": 3
    },
    "target_devices": {
      "type": "array",
      "title": "Target Devices",
      "description": "List of target device names to install the policy package to. At least one target device or target device group must be provided",
      "items": {
        "type": "string"
      },
      "order": 2
    }
  },
  "required": [
    "policy_package"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class InstallPolicyPackageOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "task_id": {
      "type": "integer",
      "title": "Task ID",
      "description": "Task identifier for the initiated install operation",
      "order": 1
    }
  },
  "required": [
    "task_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
