# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Check if an address exists in an address group"


class Input:
    ADDRESS = "address"
    ADOM = "adom"
    GROUP = "group"


class Output:
    ADDRESS_OBJECTS = "address_objects"
    FOUND = "found"
    MESSAGE = "message"


class CheckIfAddressInGroupInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address": {
      "type": "string",
      "title": "Address",
      "description": "The address to look for. Matches against both address object names and stored values, so an object name, an IP address, a CIDR range, or an FQDN are all accepted",
      "order": 1
    },
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 3
    },
    "group": {
      "type": "string",
      "title": "Group",
      "description": "Name of the address group to check",
      "order": 2
    }
  },
  "required": [
    "address",
    "group"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CheckIfAddressInGroupOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_objects": {
      "type": "array",
      "title": "Address Objects",
      "description": "List of matching address object names found in the group",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "found": {
      "type": "boolean",
      "title": "Found",
      "description": "Whether at least one matching address object was found in the group",
      "order": 1
    },
    "message": {
      "type": "string",
      "title": "Message",
      "description": "Human-readable description of the result",
      "order": 3
    }
  },
  "required": [
    "address_objects",
    "found"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
