# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Check if an address exists in an address group"


class Input:
    ADDRESS = "address"
    ADOM = "adom"
    ENABLE_SEARCH = "enable_search"
    GROUP = "group"


class Output:
    ADDRESS_OBJECTS = "address_objects"
    FOUND = "found"


class CheckIfAddressInGroupInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address": {
      "type": "string",
      "title": "Address",
      "description": "The address to check. When Enable Search is false, this is matched against address object names. When Enable Search is true, this is matched against the stored subnet or FQDN value of each member object",
      "order": 1
    },
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 4
    },
    "enable_search": {
      "type": "boolean",
      "title": "Enable Search",
      "description": "When enabled, the address input is compared against the stored value (subnet/FQDN) of each member object rather than matching by name",
      "default": false,
      "order": 3
    },
    "group": {
      "type": "string",
      "title": "Group",
      "description": "Name of the address group to check",
      "order": 2
    }
  },
  "required": [
    "address",
    "enable_search",
    "group"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CheckIfAddressInGroupOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_objects": {
      "type": "array",
      "title": "Address Objects",
      "description": "List of matching address object names found in the group",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "found": {
      "type": "boolean",
      "title": "Found",
      "description": "Whether at least one matching address object was found in the group",
      "order": 1
    }
  },
  "required": [
    "address_objects",
    "found"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
