# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Submit a suspicious script or command for AI-powered explanation with security context"


class Input:
    CONTEXT = "context"
    SCRIPT = "script"
    SCRIPT_TYPE = "script_type"


class Output:
    EXPLANATION = "explanation"
    INDICATORS = "indicators"
    RISK_LEVEL = "risk_level"
    TECHNIQUES = "techniques"


class ExplainScriptInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "context": {
      "type": "string",
      "title": "Context",
      "description": "Optional context about where the script was found (e.g., email attachment, scheduled task, registry)",
      "placeholder": "Describe where the script was found",
      "order": 3
    },
    "script": {
      "type": "string",
      "title": "Script",
      "description": "The script content or command to analyze and explain",
      "placeholder": "Paste the script or command",
      "order": 1
    },
    "script_type": {
      "type": "string",
      "title": "Script Type",
      "description": "The type or language of the script",
      "enum": [
        "powershell",
        "bash",
        "python",
        "batch",
        "vbscript",
        "javascript",
        "unknown"
      ],
      "order": 2
    }
  },
  "required": [
    "script"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ExplainScriptOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "explanation": {
      "type": "string",
      "title": "Explanation",
      "description": "Human-readable explanation of what the script does",
      "order": 1
    },
    "indicators": {
      "type": "array",
      "title": "Indicators",
      "description": "Any IOCs extracted from the script (URLs, IPs, domains, hashes)",
      "items": {
        "type": "string"
      },
      "order": 4
    },
    "risk_level": {
      "type": "string",
      "title": "Risk Level",
      "description": "Assessment of the script's risk level",
      "order": 2
    },
    "techniques": {
      "type": "array",
      "title": "Techniques",
      "description": "MITRE ATT&CK techniques or attack patterns identified in the script",
      "items": {
        "type": "string"
      },
      "order": 3
    }
  },
  "required": [
    "explanation",
    "indicators",
    "risk_level",
    "techniques"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
