# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get AI-recommended response and containment actions for a security incident"


class Input:
    ENVIRONMENT_CONTEXT = "environment_context"
    INCIDENT_DESCRIPTION = "incident_description"
    RESPONSE_PHASE = "response_phase"


class Output:
    IMMEDIATE_ACTIONS = "immediate_actions"
    INVESTIGATION_STEPS = "investigation_steps"
    LONG_TERM_RECOMMENDATIONS = "long_term_recommendations"


class SuggestResponseActionsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "environment_context": {
      "type": "string",
      "title": "Environment Context",
      "description": "Optional context about the environment (network segmentation, critical assets, existing controls)",
      "placeholder": "Describe the environment",
      "order": 2
    },
    "incident_description": {
      "type": "string",
      "title": "Incident Description",
      "description": "Description of the security incident requiring response recommendations",
      "placeholder": "Describe the security incident",
      "order": 1
    },
    "response_phase": {
      "type": "string",
      "title": "Response Phase",
      "description": "Current phase of incident response to tailor recommendations",
      "default": "containment",
      "enum": [
        "identification",
        "containment",
        "eradication",
        "recovery",
        "lessons_learned"
      ],
      "order": 3
    }
  },
  "required": [
    "incident_description"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SuggestResponseActionsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "immediate_actions": {
      "type": "array",
      "title": "Immediate Actions",
      "description": "Prioritized list of immediate actions to take",
      "items": {
        "type": "string"
      },
      "order": 1
    },
    "investigation_steps": {
      "type": "array",
      "title": "Investigation Steps",
      "description": "Recommended investigation steps to determine scope and impact",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "long_term_recommendations": {
      "type": "array",
      "title": "Long-Term Recommendations",
      "description": "Strategic recommendations to prevent recurrence",
      "items": {
        "type": "string"
      },
      "order": 3
    }
  },
  "required": [
    "immediate_actions",
    "investigation_steps",
    "long_term_recommendations"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
