# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Submit an indicator of compromise (IP, domain, hash, or URL) to ChatGPT for threat context analysis"


class Input:
    ADDITIONAL_CONTEXT = "additional_context"
    INDICATOR = "indicator"
    INDICATOR_TYPE = "indicator_type"


class Output:
    ANALYSIS = "analysis"
    RECOMMENDED_ACTIONS = "recommended_actions"
    RISK_ASSESSMENT = "risk_assessment"


class AnalyzeIndicatorInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "additional_context": {
      "type": "string",
      "title": "Additional Context",
      "description": "Optional additional context about where this indicator was observed",
      "placeholder": "Describe where the indicator was found",
      "order": 3
    },
    "indicator": {
      "type": "string",
      "title": "Indicator",
      "description": "The indicator of compromise to analyze (IP address, domain, file hash, or URL)",
      "placeholder": "Enter an IOC (IP, domain, hash, or URL)",
      "order": 1
    },
    "indicator_type": {
      "type": "string",
      "title": "Indicator Type",
      "description": "The type of indicator being submitted",
      "enum": [
        "ip_address",
        "domain",
        "file_hash",
        "url"
      ],
      "order": 2
    }
  },
  "required": [
    "indicator",
    "indicator_type"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AnalyzeIndicatorOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "analysis": {
      "type": "string",
      "title": "Analysis",
      "description": "AI-generated threat analysis of the indicator",
      "order": 1
    },
    "recommended_actions": {
      "type": "array",
      "title": "Recommended Actions",
      "description": "List of recommended response actions based on the analysis",
      "items": {
        "type": "string"
      },
      "order": 3
    },
    "risk_assessment": {
      "type": "string",
      "title": "Risk Assessment",
      "description": "Brief risk level assessment based on the analysis",
      "order": 2
    }
  },
  "required": [
    "analysis",
    "recommended_actions",
    "risk_assessment"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
