# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add a domain or email address to a blocking transport rule in Exchange Admin Center. In Office 365 cloud, transport rules are limited to 8k of data or roughly 8100 characters. This is roughly 400 email addresses. If a new email address is added (that would break that limit), existing emails would need to be manually deleted to make room for new additions"


class Input:
    DOMAIN_OR_EMAIL_TO_BLOCK = "domain_or_email_to_block"
    TRANSPORT_RULE_NAME = "transport_rule_name"


class Output:
    RESULT = "result"


class BlockSenderTransportRuleInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "domain_or_email_to_block": {
      "type": "string",
      "title": "Domain or Email to Block",
      "description": "Domain or email address to block",
      "order": 1
    },
    "transport_rule_name": {
      "type": "string",
      "title": "Transport Rule Name",
      "description": "Name of transport rule",
      "default": "InsightConnect Block List",
      "order": 2
    }
  },
  "required": [
    "domain_or_email_to_block",
    "transport_rule_name"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class BlockSenderTransportRuleOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "result": {
      "type": "string",
      "title": "Result",
      "description": "Result",
      "order": 1
    }
  },
  "required": [
    "result"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
