# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve entries from the Tenant Allow/Block List filtered by list type and action"


class Input:
    ACTION_TYPE = "action_type"
    LIST_TYPE = "list_type"


class Output:
    ENTRIES = "entries"


class GetTenantAllowBlockListItemsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "action_type": {
      "type": "string",
      "title": "Action Type",
      "description": "Filter by allow or block entries. Leave empty to return both",
      "enum": [
        "Allow",
        "Block",
        ""
      ],
      "order": 2
    },
    "list_type": {
      "type": "string",
      "title": "List Type",
      "description": "The type of entries to retrieve",
      "enum": [
        "Sender",
        "Url",
        "FileHash",
        "IP"
      ],
      "order": 1
    }
  },
  "required": [
    "list_type"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetTenantAllowBlockListItemsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "entries": {
      "type": "array",
      "title": "Entries",
      "description": "List of Tenant Allow/Block List entries",
      "items": {
        "$ref": "#/definitions/tenant_allow_block_list_entry"
      },
      "order": 1
    }
  },
  "required": [
    "entries"
  ],
  "definitions": {
    "tenant_allow_block_list_entry": {
      "type": "object",
      "title": "tenant_allow_block_list_entry",
      "properties": {
        "Identity": {
          "type": "string",
          "title": "Identity",
          "description": "Unique identifier of the entry",
          "order": 1
        },
        "Value": {
          "type": "string",
          "title": "Value",
          "description": "The blocked or allowed value (URL, sender, file hash, or IP)",
          "order": 2
        },
        "Action": {
          "type": "string",
          "title": "Action",
          "description": "Whether this is an Allow or Block entry",
          "order": 3
        },
        "ListType": {
          "type": "string",
          "title": "List Type",
          "description": "The type of entry (Sender, URL, FileHash, or IP)",
          "order": 4
        },
        "ExpirationDate": {
          "type": "string",
          "title": "Expiration Date",
          "description": "The expiration date of the entry in UTC",
          "order": 5
        },
        "Notes": {
          "type": "string",
          "title": "Notes",
          "description": "Notes associated with the entry",
          "order": 6
        },
        "LastModifiedDateTime": {
          "type": "string",
          "title": "Last Modified Date Time",
          "description": "When the entry was last modified",
          "order": 7
        },
        "CreatedDateTime": {
          "type": "string",
          "title": "Created Date Time",
          "description": "When the entry was created",
          "order": 8
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
