# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve firewall policies from a FortiManager policy package"


class Input:
    ADOM = "adom"
    NAME_FILTER = "name_filter"
    POLICY_PACKAGE = "policy_package"


class Output:
    POLICIES = "policies"


class GetPoliciesInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 3
    },
    "name_filter": {
      "type": "string",
      "title": "Name Filter",
      "description": "Optional policy name to filter on (case-insensitive exact match)",
      "order": 2
    },
    "policy_package": {
      "type": "string",
      "title": "Policy Package",
      "description": "Name of the policy package to retrieve policies from",
      "order": 1
    }
  },
  "required": [
    "policy_package"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetPoliciesOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "policies": {
      "type": "array",
      "title": "Policies",
      "description": "List of firewall policies matching the specified filters",
      "items": {
        "$ref": "#/definitions/policy"
      },
      "order": 1
    }
  },
  "required": [
    "policies"
  ],
  "definitions": {
    "policy": {
      "type": "object",
      "title": "policy",
      "properties": {
        "policyid": {
          "type": "integer",
          "title": "Policy ID",
          "description": "Firewall policy ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Policy name",
          "order": 2
        },
        "srcintf": {
          "type": "array",
          "title": "Source Interface",
          "description": "Source interfaces",
          "items": {
            "type": "string"
          },
          "order": 3
        },
        "dstintf": {
          "type": "array",
          "title": "Destination Interface",
          "description": "Destination interfaces",
          "items": {
            "type": "string"
          },
          "order": 4
        },
        "srcaddr": {
          "type": "array",
          "title": "Source Address",
          "description": "Source address objects or groups",
          "items": {
            "type": "string"
          },
          "order": 5
        },
        "dstaddr": {
          "type": "array",
          "title": "Destination Address",
          "description": "Destination address objects or groups",
          "items": {
            "type": "string"
          },
          "order": 6
        },
        "service": {
          "type": "array",
          "title": "Service",
          "description": "Service objects",
          "items": {
            "type": "string"
          },
          "order": 7
        },
        "action": {
          "type": "string",
          "title": "Action",
          "description": "Policy action: accept, deny, ipsec",
          "order": 8
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Policy status: enable, disable",
          "order": 9
        },
        "schedule": {
          "type": "string",
          "title": "Schedule",
          "description": "Schedule name",
          "order": 10
        },
        "logtraffic": {
          "type": "string",
          "title": "Log Traffic",
          "description": "Logging mode: disable, all, utm",
          "order": 11
        },
        "comments": {
          "type": "string",
          "title": "Comments",
          "description": "Policy comments",
          "order": 12
        }
      },
      "required": [
        "name",
        "policyid"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
