# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add or remove domains from blocked domain list"


class Input:
    DOMAINS = "domains"
    IDENTITY = "identity"
    OPERATION = "operation"


class Output:
    SUCCESS = "success"


class UpdateListOfBlockedDomainsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "domains": {
      "type": "array",
      "title": "Domains",
      "description": "Domains which will be blocked",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "identity": {
      "type": "string",
      "title": "Identity",
      "description": "The Identity parameter specifies the spam filter policy that you want to view. Could be Name/Distinguished name (DN)/GUID",
      "order": 1
    },
    "operation": {
      "type": "string",
      "title": "Operation",
      "description": "Operation which will be apply on list of blocked domains",
      "enum": [
        "Add",
        "Remove"
      ],
      "order": 3
    }
  },
  "required": [
    "domains",
    "identity",
    "operation"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateListOfBlockedDomainsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Success of operation",
      "order": 1
    }
  },
  "required": [
    "success"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
