# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="rapid7_velociraptor-rapid7-plugin",
    version="1.0.0",
    description="Manage endpoint collections, hunts, and artifact deployments using the Rapid7 Velociraptor API",
    author="rapid7",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_rapid7_velociraptor = bin.icon_rapid7_velociraptor:main"]},
)
