# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Purge a provided email"


class Input:
    COMPLIANCE_SEARCH_NAME = "compliance_search_name"
    QUERY_TIMEOUT = "query_timeout"


class Output:
    SUCCESS = "success"


class MassPurgeInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "compliance_search_name": {
      "type": "string",
      "title": "Compliance Search Name",
      "description": "Name of compliance search",
      "order": 1
    },
    "query_timeout": {
      "type": "integer",
      "title": "Query Timeout",
      "description": "Query timeout in minutes",
      "default": 60,
      "order": 2
    }
  },
  "required": [
    "compliance_search_name"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class MassPurgeOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Success",
      "order": 1
    }
  },
  "required": [
    "success"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
