# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = (
        "Look up geolocation data for up to 100 IPv4 addresses, IPv6 addresses, or domain names in a single request"
    )


class Input:
    LANG = "lang"
    QUERIES = "queries"


class Output:
    RESULTS = "results"


class GeolocateBulkInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "lang": {
      "type": "string",
      "title": "Language",
      "description": "Language for localized city and country names",
      "default": "en",
      "enum": [
        "en",
        "de",
        "es",
        "pt-BR",
        "fr",
        "ja",
        "zh-CN",
        "ru"
      ],
      "order": 2
    },
    "queries": {
      "type": "array",
      "title": "Queries",
      "description": "List of IPv4 addresses, IPv6 addresses, or domain names to look up (maximum 100)",
      "items": {
        "type": "string"
      },
      "order": 1
    }
  },
  "required": [
    "queries"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GeolocateBulkOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "array",
      "title": "Results",
      "description": "List of geolocation results for the queried IPs or domains",
      "items": {
        "$ref": "#/definitions/geolocation_result"
      },
      "order": 1
    }
  },
  "definitions": {
    "geolocation_result": {
      "type": "object",
      "title": "geolocation_result",
      "properties": {
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Query status, either success or fail",
          "order": 1
        },
        "message": {
          "type": "string",
          "title": "Message",
          "description": "Failure reason when status is fail",
          "order": 2
        },
        "continent": {
          "type": "string",
          "title": "Continent",
          "description": "Continent name",
          "order": 3
        },
        "continentCode": {
          "type": "string",
          "title": "Continent Code",
          "description": "Two-letter continent code",
          "order": 4
        },
        "country": {
          "type": "string",
          "title": "Country",
          "description": "Country name",
          "order": 5
        },
        "countryCode": {
          "type": "string",
          "title": "Country Code",
          "description": "Two-letter country code (ISO 3166-1 alpha-2)",
          "order": 6
        },
        "region": {
          "type": "string",
          "title": "Region",
          "description": "Region or state code",
          "order": 7
        },
        "regionName": {
          "type": "string",
          "title": "Region Name",
          "description": "Region or state name",
          "order": 8
        },
        "city": {
          "type": "string",
          "title": "City",
          "description": "City name",
          "order": 9
        },
        "district": {
          "type": "string",
          "title": "District",
          "description": "District name",
          "order": 10
        },
        "zip": {
          "type": "string",
          "title": "ZIP Code",
          "description": "ZIP or postal code",
          "order": 11
        },
        "lat": {
          "type": "number",
          "title": "Latitude",
          "description": "Latitude",
          "order": 12
        },
        "lon": {
          "type": "number",
          "title": "Longitude",
          "description": "Longitude",
          "order": 13
        },
        "timezone": {
          "type": "string",
          "title": "Timezone",
          "description": "City timezone (tz database format)",
          "order": 14
        },
        "offset": {
          "type": "integer",
          "title": "UTC Offset",
          "description": "Timezone UTC DST offset in seconds",
          "order": 15
        },
        "currency": {
          "type": "string",
          "title": "Currency",
          "description": "National currency",
          "order": 16
        },
        "isp": {
          "type": "string",
          "title": "ISP",
          "description": "Internet Service Provider name",
          "order": 17
        },
        "org": {
          "type": "string",
          "title": "Organization",
          "description": "Organization name",
          "order": 18
        },
        "as_number": {
          "type": "string",
          "title": "AS Number",
          "description": "AS number and name (e.g. AS15169 Google LLC)",
          "order": 19
        },
        "asname": {
          "type": "string",
          "title": "AS Name",
          "description": "AS name (RIR)",
          "order": 20
        },
        "reverse": {
          "type": "string",
          "title": "Reverse DNS",
          "description": "Reverse DNS of the IP",
          "order": 21
        },
        "mobile": {
          "type": "boolean",
          "title": "Mobile",
          "description": "Mobile (cellular) connection",
          "order": 22
        },
        "proxy": {
          "type": "boolean",
          "title": "Proxy",
          "description": "Proxy, VPN, or Tor exit address",
          "order": 23
        },
        "hosting": {
          "type": "boolean",
          "title": "Hosting",
          "description": "Hosting, colocated, or data center",
          "order": 24
        },
        "query": {
          "type": "string",
          "title": "Query",
          "description": "IP address or domain used in the query",
          "order": 25
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
