# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add an address object to an address group in a FortiManager ADOM"


class Input:
    ADDRESS_OBJECT = "address_object"
    ADOM = "adom"
    GROUP = "group"


class Output:
    ADDRESS_OBJECTS = "address_objects"
    SUCCESS = "success"


class AddAddressObjectToGroupInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_object": {
      "type": "string",
      "title": "Address Object",
      "description": "Name of the address object to add to the group",
      "order": 1
    },
    "adom": {
      "type": "string",
      "title": "ADOM",
      "description": "Administrative Domain for the operation. If provided, overrides the ADOM configured in the connection",
      "order": 3
    },
    "group": {
      "type": "string",
      "title": "Group",
      "description": "Name of the address group",
      "order": 2
    }
  },
  "required": [
    "address_object",
    "group"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddAddressObjectToGroupOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "address_objects": {
      "type": "array",
      "title": "Address Objects",
      "description": "Updated list of address object names in the group",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Boolean value indicating the success of the operation",
      "order": 1
    }
  },
  "required": [
    "address_objects",
    "success"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
