# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add a VPN gateway bypass entry to a ZCC application profile. If the entry already exists, the action succeeds without duplicating it (idempotent)"


class Input:
    ENTRY = "entry"
    PROFILE_ID = "profile_id"


class Output:
    SUCCESS = "success"
    VPN_GATEWAYS = "vpn_gateways"


class AddVpnGatewayBypassInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "entry": {
      "type": "string",
      "title": "Entry",
      "description": "The hostname or IP address to add to VPN gateway bypasses",
      "order": 2
    },
    "profile_id": {
      "type": "string",
      "title": "Profile ID",
      "description": "The profile ID to update",
      "order": 1
    }
  },
  "required": [
    "entry",
    "profile_id"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddVpnGatewayBypassOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the addition was successful",
      "order": 1
    },
    "vpn_gateways": {
      "type": "array",
      "title": "VPN Gateways",
      "description": "Updated list of VPN gateway bypass entries after the addition",
      "items": {
        "$ref": "#/definitions/vpn_gateway_entry"
      },
      "order": 2
    }
  },
  "required": [
    "success",
    "vpn_gateways"
  ],
  "definitions": {
    "vpn_gateway_entry": {
      "type": "object",
      "title": "vpn_gateway_entry",
      "properties": {
        "hostname": {
          "type": "string",
          "title": "Hostname",
          "description": "The hostname of the VPN gateway bypass entry",
          "order": 1
        },
        "ip": {
          "type": "string",
          "title": "IP",
          "description": "The IP address of the VPN gateway bypass entry",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "The type of entry (e.g., \"hostname\", \"ip\")",
          "order": 3
        }
      }
    }
  }
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
