# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    BASE_URL = "base_url"
    CLIENT_ID = "client_id"
    CLIENT_SECRET = "client_secret"
    TENANT = "tenant"


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "base_url": {
      "type": "string",
      "title": "Base URL",
      "description": "Base URL of your Halo ITSM instance (e.g. https://your-instance.haloitsm.com)",
      "order": 1
    },
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "OAuth Client ID for the Halo ITSM API application",
      "order": 2
    },
    "client_secret": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "Client Secret",
      "description": "OAuth Client Secret for the Halo ITSM API application",
      "order": 3
    },
    "tenant": {
      "type": "string",
      "title": "Tenant",
      "description": "Tenant name for multi-tenant Halo ITSM instances (optional, leave blank if not applicable)",
      "order": 4
    }
  },
  "required": [
    "base_url",
    "client_id",
    "client_secret"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "required": [
        "secretKey"
      ],
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "description": "The shared secret key",
          "format": "password",
          "displayType": "password"
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
