# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="zscaler-rapid7_mnp-plugin",
    version="2.2.0",
    description="Zscaler is a SaaS security platform that provides fast, secure connections between client applications, regardless of device, location, or network",
    author="rapid7_mnp",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_zscaler = bin.icon_zscaler:main"]},
)
