# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Browse available Velociraptor artifact definitions for use in collections and hunts"


class Input:
    ARTIFACT_TYPE = "artifact_type"
    INCLUDE_BUILT_IN = "include_built_in"
    INCLUDE_CUSTOM = "include_custom"
    OS = "os"


class Output:
    ARTIFACTS = "artifacts"
    COUNT = "count"


class ListArtifactsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "artifact_type": {
      "type": "string",
      "title": "Artifact Type",
      "description": "Filter by artifact type",
      "default": "ALL",
      "enum": [
        "ALL",
        "CLIENT",
        "CLIENT_EVENT",
        "SERVER",
        "SERVER_EVENT",
        "NOTEBOOK"
      ],
      "order": 1
    },
    "include_built_in": {
      "type": "boolean",
      "title": "Include Built-In",
      "description": "Include built-in artifacts in results",
      "default": true,
      "order": 3
    },
    "include_custom": {
      "type": "boolean",
      "title": "Include Custom",
      "description": "Include custom artifacts in results",
      "default": true,
      "order": 4
    },
    "os": {
      "type": "string",
      "title": "Operating System",
      "description": "Filter by target operating system",
      "default": "ALL",
      "enum": [
        "ALL",
        "LINUX",
        "WINDOWS",
        "DARWIN"
      ],
      "order": 2
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ListArtifactsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "artifacts": {
      "type": "array",
      "title": "Artifacts",
      "description": "List of available artifact definitions",
      "items": {
        "$ref": "#/definitions/artifact_listing"
      },
      "order": 1
    },
    "count": {
      "type": "integer",
      "title": "Count",
      "description": "Number of artifacts returned",
      "order": 2
    }
  },
  "definitions": {
    "artifact_listing": {
      "type": "object",
      "title": "artifact_listing",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "order": 1
        },
        "description": {
          "type": "string",
          "title": "Description",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "order": 3
        },
        "built_in": {
          "type": "boolean",
          "title": "Built In",
          "order": 4
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
