# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="ip_api-rapid7-plugin",
    version="1.0.0",
    description="Geolocate IPv4 addresses, IPv6 addresses, and domain names using the ip-api.com service",
    author="rapid7",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_ip_api = bin.icon_ip_api:main"]},
)
