# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Create a new fleet-wide threat hunt to collect artifacts across multiple endpoints"


class Input:
    ARTIFACTS = "artifacts"
    CLIENT_LIMIT = "client_limit"
    EXCLUDE_LABELS = "exclude_labels"
    EXPIRES = "expires"
    HUNT_DESCRIPTION = "hunt_description"
    INCLUDE_LABELS = "include_labels"
    OS_CONDITION = "os_condition"


class Output:
    HUNT_ID = "hunt_id"


class CreateHuntInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "artifacts": {
      "type": "array",
      "title": "Artifacts",
      "description": "List of artifact names to collect in this hunt",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "client_limit": {
      "type": "integer",
      "title": "Client Limit",
      "description": "Maximum number of clients to schedule the hunt on",
      "order": 6
    },
    "exclude_labels": {
      "type": "array",
      "title": "Exclude Labels",
      "description": "Exclude clients with these labels",
      "items": {
        "type": "string"
      },
      "order": 5
    },
    "expires": {
      "type": "integer",
      "title": "Expires",
      "description": "Hunt expiration time as a Unix timestamp",
      "order": 7
    },
    "hunt_description": {
      "type": "string",
      "title": "Hunt Description",
      "description": "A description of the hunt purpose",
      "placeholder": "Hunt for suspicious PowerShell activity",
      "order": 1
    },
    "include_labels": {
      "type": "array",
      "title": "Include Labels",
      "description": "Only target clients with these labels",
      "items": {
        "type": "string"
      },
      "order": 4
    },
    "os_condition": {
      "type": "string",
      "title": "OS Condition",
      "description": "Target operating system for the hunt",
      "default": "ALL",
      "enum": [
        "ALL",
        "WINDOWS",
        "LINUX",
        "OSX"
      ],
      "order": 3
    }
  },
  "required": [
    "artifacts",
    "hunt_description"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateHuntOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hunt_id": {
      "type": "string",
      "title": "Hunt ID",
      "description": "The unique identifier of the created hunt",
      "order": 1
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
