# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add a new entry to the Tenant Allow/Block List to block or allow senders, URLs, file hashes, or IPs"


class Input:
    ACTION_TYPE = "action_type"
    ENTRIES = "entries"
    EXPIRATION_DAYS = "expiration_days"
    LIST_TYPE = "list_type"
    NO_EXPIRATION = "no_expiration"
    NOTES = "notes"


class Output:
    ENTRIES = "entries"
    SUCCESS = "success"


class CreateTenantAllowBlockListEntryInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "action_type": {
      "type": "string",
      "title": "Action Type",
      "description": "Whether to create an allow or block entry",
      "enum": [
        "Allow",
        "Block"
      ],
      "order": 3
    },
    "entries": {
      "type": "array",
      "title": "Entries",
      "description": "Values to add to the list. For Sender use email or domain, for URL use the URL value, for FileHash use SHA256 hashes, for IP use IPv6 addresses or CIDR ranges",
      "placeholder": "evil@example.com, malicious-domain.com",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "expiration_days": {
      "type": "integer",
      "title": "Expiration Days",
      "description": "Number of days until the entry expires (default 30 if no_expiration is false). Ignored if no_expiration is true",
      "default": 30,
      "order": 5
    },
    "list_type": {
      "type": "string",
      "title": "List Type",
      "description": "The type of entry to create",
      "enum": [
        "Sender",
        "Url",
        "FileHash",
        "IP"
      ],
      "order": 1
    },
    "no_expiration": {
      "type": "boolean",
      "title": "No Expiration",
      "description": "If true, the entry will never expire. Only valid for block entries",
      "default": false,
      "order": 4
    },
    "notes": {
      "type": "string",
      "title": "Notes",
      "description": "Optional notes to associate with the entry",
      "placeholder": "Blocked due to phishing campaign",
      "order": 6
    }
  },
  "required": [
    "action_type",
    "entries",
    "list_type"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateTenantAllowBlockListEntryOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "entries": {
      "type": "array",
      "title": "Entries",
      "description": "The created Tenant Allow/Block List entries",
      "items": {
        "$ref": "#/definitions/tenant_allow_block_list_entry"
      },
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the entries were created successfully",
      "order": 1
    }
  },
  "required": [
    "entries",
    "success"
  ],
  "definitions": {
    "tenant_allow_block_list_entry": {
      "type": "object",
      "title": "tenant_allow_block_list_entry",
      "properties": {
        "Identity": {
          "type": "string",
          "title": "Identity",
          "description": "Unique identifier of the entry",
          "order": 1
        },
        "Value": {
          "type": "string",
          "title": "Value",
          "description": "The blocked or allowed value (URL, sender, file hash, or IP)",
          "order": 2
        },
        "Action": {
          "type": "string",
          "title": "Action",
          "description": "Whether this is an Allow or Block entry",
          "order": 3
        },
        "ListType": {
          "type": "string",
          "title": "List Type",
          "description": "The type of entry (Sender, URL, FileHash, or IP)",
          "order": 4
        },
        "ExpirationDate": {
          "type": "string",
          "title": "Expiration Date",
          "description": "The expiration date of the entry in UTC",
          "order": 5
        },
        "Notes": {
          "type": "string",
          "title": "Notes",
          "description": "Notes associated with the entry",
          "order": 6
        },
        "LastModifiedDateTime": {
          "type": "string",
          "title": "Last Modified Date Time",
          "description": "When the entry was last modified",
          "order": 7
        },
        "CreatedDateTime": {
          "type": "string",
          "title": "Created Date Time",
          "description": "When the entry was created",
          "order": 8
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
