# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Return spam filter policies in your cloud based organization"


class Input:
    pass


class Output:
    SPAM_POLICY = "spam_policy"


class GetListOfBlockedDomainsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetListOfBlockedDomainsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "spam_policy": {
      "type": "array",
      "title": "Spam Policy",
      "description": "Information about blocked sender domain",
      "items": {
        "$ref": "#/definitions/spam_policy"
      },
      "order": 1
    }
  },
  "required": [
    "spam_policy"
  ],
  "definitions": {
    "spam_policy": {
      "type": "object",
      "title": "spam_policy",
      "properties": {
        "Name": {
          "type": "string",
          "title": "Name",
          "description": "Name of policy",
          "order": 1
        },
        "DistinguishedName": {
          "type": "string",
          "title": "Distinguished Name",
          "description": "Distinguished name (DN)",
          "order": 2
        },
        "Guid": {
          "type": "string",
          "title": "GUID",
          "description": "GUID attribute",
          "order": 3
        },
        "BlockedSenderDomains": {
          "type": "array",
          "title": "Blocked Sender Domains",
          "description": "List of blocked sender domains",
          "items": {
            "type": "string"
          },
          "order": 4
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
